from cgpt.app.utils.constant import ADDRESS_NOT_VALID
from cgpt.app.utils.constant import CONNECTION_ERROR
from cgpt.app.utils.constant import CONNECTION_IMPOSSIBLE
from cgpt.app.utils.constant import DASHED
from cgpt.app.utils.constant import ENTER_SERVER_IP
from cgpt.app.utils.constant import IA
from cgpt.app.utils.constant import PORT
from cgpt.app.utils.constant import SAY_SOMETHING
from cgpt.app.utils.constant import UTF
from cgpt.app.utils.constant import error_color
